version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
  build:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: node --version
workflows:
  build_test_publish:
    jobs:
      - install-node-example